# Generated by Django 5.2.15 on 2026-06-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shorturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
